// Fumadocs imports Lucide internally. The Vite alias maps those names to Phosphor.
export {
  ArrowSquareOutIcon as ExternalLink,
  ArrowSquareOutIcon as ExternalLinkIcon,
  CaretDownIcon as ChevronDown,
  CaretLeftIcon as ChevronLeft,
  CaretRightIcon as ChevronRight,
  CaretUpDownIcon as ChevronsUpDown,
  ChatCircleIcon as MessageCircleIcon,
  CheckCircleIcon as CircleCheck,
  CheckIcon as Check,
  ChecksIcon as CopyCheckIcon,
  ClipboardIcon as Clipboard,
  CopyIcon as Copy,
  FileIcon,
  FolderIcon,
  FolderOpenIcon as FolderOpen,
  GitForkIcon as GitFork,
  HashIcon as Hash,
  HouseIcon as HomeIcon,
  InfoIcon as Info,
  LightbulbIcon as Lightbulb,
  LinkIcon,
  MagnifyingGlassIcon as Search,
  MagnifyingGlassIcon as SearchIcon,
  MonitorIcon as Airplay,
  MoonIcon as Moon,
  PencilSimpleIcon as Edit,
  SidebarSimpleIcon as Sidebar,
  SidebarSimpleIcon as SidebarIcon,
  StarIcon as Star,
  SunIcon as Sun,
  TextAlignLeftIcon as Text,
  TextAlignLeftIcon as TextIcon,
  TranslateIcon as Languages,
  TranslateIcon as LanguagesIcon,
  WarningIcon as TriangleAlert,
  XCircleIcon as CircleX,
  XIcon as X,
  XIcon,
} from "@phosphor-icons/react/ssr";
